### ISSUE TITLE
Filter by age

### ISSUE THREAD

**Issue by Tigermanic** [howlrapp/howlr-app#10]
With all the ways you can filter profiles, I'm very surprised I can't filter by age. Or perhaps I'm just blind?

**Comment by dustyboyo** [comment]
I really would like to have a age filter honestly it really helps a lot! Because you might wanna make some friends with furs who are either close to or are your own age, but it’s hard to do when there is no age filter

**Comment by soatok** [comment]
This existed in a previous version of the app. I don't know why it was removed.

**Comment by dustyboyo** [comment]
Well I think they should put it back in the app

**Comment by howlrapp** [comment]
The new age range filter is done and will be deployed in the next version, thanks for your suggestion!

**Comment by Tigermanic** [comment]
Thank you so much!
