### ISSUE TITLE
Offer for Purchase

### ISSUE THREAD

**Issue by Dax911** [howlrapp/howlr-app#14]
Hello,

I would like to discuss taking over development or otherwise purchasing Howlr in order to continue its development as a commercially viable app with more features and support. Please let me know. I can be reached at my company email Hayden@flynntech.io

Big fan,

Dax

**Comment by howlrapp** [comment]
Hello there!

Thanks for your proposal! However Howlr is a non-profit and our organisation status doesn't allow for reselling anyway. However let me know if you would be interested in spinning your own server as a beta user once we are ready for it.

Have a great day!
