### ISSUE TITLE
iPhone 12 Pro unexpected heating up on DM prompts

### ISSUE THREAD

**Issue by dev-sda1** [howlrapp/howlr-app#28]
Sometimes when using the messaging function on the app, my phone starts to become inexplicibly warm, sometimes starting to get incredibly hot. Seemed to take me a good 10-15 minutes before my phone started heating up for some reason.

Repo steps:
Open a DM between someone
Wait for an amount of time (I had it happen after 10-15 minutes, not sure if it varies depending on phone)
You'll feel phone start to warm up because of exessive resource usage.

**Comment by howlrapp** [comment]
Hello @dev-sda1 and thanks a lot for your bug report! I realised that I made a very dumb mistake with the way we handle push events from the server. It should be fixed now, can you reload the app twice (to download the last javascript payload and execute it) and tell us if you're still experiencing this issue?

Thanks again and have a great day!

**Comment by dev-sda1** [comment]
Seems to all be good now. Thanks!
