### ISSUE TITLE
Filter Options Spacing

### ISSUE THREAD

**Issue by Blykam** [howlrapp/howlr-app#36]
The space in between filter options are weird and not homogenous. Pls fix it, so all options are spaced evenly

**Comment by howlrapp** [comment]
Hello! Can you provide a screenshot so I can better see what you mean? Thank you!

**Comment by howlrapp** [comment]
Oh okay I think i see it now x)

**Comment by howlrapp** [comment]
Okay I rolled back my changes and left it the way it was intended by the component library (meaning a small bottom padding at the end of the list). Funny how I was so focused by the bottom padding that the top padding was totally obscured in my mind. Thanks for reporting it! Reload Howlr twice to see the change
