### ISSUE TITLE
Unit Testing of Application

### ISSUE THREAD

**Issue by Dax911** [howlrapp/howlr-app#4]
The purpose of this (epic sized) issue is to drive the app towards better and more complete testing so that we can support making changes without worrying about creating new bugs.

**Comment by howlrapp** [comment]
Oh yes it needs it! I know that once I have a first bit of code coverage I want to max it out to 100%. We tried Detox recently for some easy e2e testing, but configuring it for Expo custom builds just gave us a bad case of JS fatigue. We will try something else in a few days.

**Comment by howlrapp** [comment]
(I would like to add that the backend is 100% covered, but Rails doesn't change every 6 months so it's way easier to get started and keep things clean x3)

**Comment by howlrapp** [comment]
Closing this ticket since there is no plan to maintain this application much further.

Thanks for your suggestion and have a great day!
