### ISSUE TITLE
account deletion request

### ISSUE THREAD

**Issue by Alexbeari18** [howlrapp/howlr-app#46]
request that my account be deleted got locked out and no longer wish to use 
![IMG_0983](https://user-images.githubusercontent.com/76024412/130309789-63c7c2cd-f4f2-4b5c-b093-c783b5a14aca.PNG)

**Comment by howlrapp** [comment]
Hello there,

Can you report this account on Howlr?

Have a great day!

**Comment by Alexbeari18** [comment]
will do
