### ISSUE TITLE
Consider publishing the app on FDroid

### ISSUE THREAD

**Issue by Furikuda** [howlrapp/howlr-app#5]
See https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md

**Comment by CazzTan** [comment]
Upping this proposal, F-Droid is a great alternative to the Play Store

**Comment by howlrapp** [comment]
That's a good idea! I think we will wait until this ticket https://github.com/howlrapp/howlr-app/issues/20 is done before we more forward with it.

**Comment by howlrapp** [comment]
After taking a look at the inclusion rules for F-Droid (https://f-droid.org/en/docs/Inclusion_Policy/) I don't think Howlr can be included:

- we use Firebase and Google libraries
- we download executable code on-the-fly 
- though it don't strictly prevent inclusion, our reliance on Telegram and non-distributed server code is an Anti-feature.

Building Expo apps locally is also pretty experimental and I'm not sure the folks at F-Droid could do it. All-in-all it seems to much of a burden, I hope this situation will change someday but in the meantime we are going to close this issue.
