### ISSUE TITLE
Is a Github release possible?

### ISSUE THREAD

**Issue by TilCreator** [howlrapp/howlr-app#52]
Hi, I just had a really bad time installing this application because the Google Play Store apparently really doesn't like me, so I had to compile the app myself. Would it be possible to release the app as Github releases, so that users that have problems with Google Play or just don't want to use it, have an alternative? I understand that Publishing on F-droid is not possible #5, but this doesn't seam like much extra work and it would be much appreciated.

**Comment by howlrapp** [comment]
Closing this ticket since there is no plan to maintain this application much further.

Thanks for your suggestion and have a great day!
