### ISSUE TITLE
Events and related notifications

### ISSUE THREAD

**Issue by OlekTk** [howlrapp/howlr-app#53]
Hi,
I have recently tried creating my first own event on Howlr.
I have noticed two possible bugs related to this process in version 39.0.0:
1) My account was listed twice on the participants' list
2) When someone else joined the event, I have received a notification stating that it was me who just joined it.

**Comment by howlrapp** [comment]
Hello!

It may be a backend bug, I'll look into it before we release it by the end of the month.

Thanks for your report!

**Comment by howlrapp** [comment]
It should be fixed when we release the server-code, thank you very much for your bug report!
