### ISSUE TITLE
Impossible Log-in

### ISSUE THREAD

**Issue by Wulfix1** [howlrapp/howlr-app#56]
I tried to log in from another device via a telegram and I got the answer "Sign-up is currently disabled"(android 10).
Besides, it is impossible to download the application from "Google Play" or "App Store", you can not even find it.
I only see it on the google account where I have it.
I haven't found any information.
Do you have any technical break or something?

**Comment by nar001** [comment]
Howlr is getting shut down, so sign ups are disabled

**Comment by Wulfix1** [comment]
Are you closing it permanently?

**Comment by nar001** [comment]
I'm not staff, just a user who both saw the notification on the app and saw the website 
![image](https://user-images.githubusercontent.com/15905072/153769069-cc64c02a-5f10-4041-9308-a6503747fe2f.png)

**Comment by howlrapp** [comment]
Hello! Yes we are closing it permanently and as such we unlisted the app and stopped accepting new users. Sorry for the inconvenience.

Have a great day!
