### ISSUE TITLE
License of name + character now that the app is discontinued?

### ISSUE THREAD

**Issue by nar001** [howlrapp/howlr-app#57]
I'm just curious what the license is for using the name and mascot, are we allowed to? Or not?

**Comment by howlrapp** [comment]
Hello!

No you are not allowed to use the name Howlr or the mascot, we will soon replace all the graphical assets in this repository with placeholder ones.

**Comment by nar001** [comment]
Fair enough! You could archive that repo too? So people know it's over, but people can still check it out/fork it?

**Comment by howlrapp** [comment]
Oh sure thing, I totally forgot that this archive feature existed.

Thank you, have a great day!
