### ISSUE TITLE
Adding method of contacting support within app?

### ISSUE THREAD

**Issue by yiffboy16** [howlrapp/howlr-app#6]
There is currently no way I can see to open a channel of communication with anyone in a moderation or administration role, either via the app or otherwise. It would be really helpful if there was at least a contact us button within the app.

Like, for example, I got banned, and there is no way to open a channel for communication to try and appeal this.

Even if in the app, it just says "go bother this person on Twitter" or something, that would be very helpful. Considering there is no guidance on what to do, it can be very confusing when a user has a reason to contact you guys, and there are no obvious ways to do it.

**Comment by p0wertiger** [comment]
There's hardly any info about authors

**Comment by yiffboy16** [comment]
Yah, that is kind of the issue. If they're fine banning without really any proof, then they should at least have SOME line of communication to get it resolved, even if it's a bloody Discord server with the moderators or something!

**Comment by howlrapp** [comment]
Hello there!

I took care of the support chat for two years and, while most users were really wonderful human beings the others managed to: denigrate our work, insult me, make me cry, prevented me from sleeping. I don't want that to happen to anybody, even if it means limiting the ways we can be contacted. It doesn't mean we aren't looking for better solutions though, we closed more than 6000 reports so this app is not lost in the limbo, but we try to find ethics way to interact with our most difficult users without burning down the benevolent moderators in the process.

I would like the stress out that this app is a benevolent work, we do the best we can, when we can and when we feel like working on it.

Now for you particular issue @yiffboy16, if you don't mind posting your Telegram handle here I'll take care of unbanning you.

**Comment by yiffboy16** [comment]
I’m sorry about that situation, and do apologies for my distaste in the matter. I didn’t know you guys ever provided support, and it’s truly sad that people would take said help, and be douches about it.

My telegram handle is identical to my GitHub one @yiffboy16 

thank you for explaining the situation a little more to me. Honestly having that be something I could’ve seen right away, would’ve made the situation a lot better, lol (I mean, before it became an issue, not as in I was complaining about when you responded. Sorry, comveyimg tone online is hard)

**Comment by howlrapp** [comment]
No worries @yiffboy16! You were banned because the birthdate you set put you under 18 when you signed up. We lifted your ban.

**Comment by yiffboy16** [comment]
Thank you for the help. I am sorry about not only how others treated the help team, but the way I went about this as well.

Maybe at some point, trying a community moderation program could work. I know I’d volunteer to help with that. I’ve learned to ignore the death threats and hate that come with being a furry.
