### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by Ami-Dragoon** [howlrapp/howlr-app#7]
I was trying to launch the app last night and it got stuck on the loading screen and wouldn't go any further. After uninstalling and reinstalling, I was brought to the login menu where you would have to enter your 6 digit code. After entering that code I am given an "Unexpected error" message. Because of this I am now unable to login.

**Comment by howlrapp** [comment]
Hello @Ami-Dragoon! Let me know if you're still experiencing this issue.
