### ISSUE TITLE
Feature Request: For Kink-Groups add categorys

### ISSUE THREAD

**Issue by Athesis** [howlrapp/howlr-app#8]
Hi! 

I would like to see a new feature for Kink-Groups to add extra information how someone relates to this kink, for example:
I'm into watching/reciving/giving/everything  *group*
Curious about watching/reciving/giving/everything *group*

**Comment by dustyboyo** [comment]
I would also like to have something new added to the kinks section, like maybe FWB (Friends with benefits) also there is a sex swing which can also a door swing of the regular thing, Idk what you would label it as but sex swing hot af I know a bunch of people who love that!

**Comment by Athesis** [comment]
Long time not happened anything here :)! 

Maybe I need to specify what I mean? 

Currently you can just joyn a group, for example "Murrsuiter", but you're unable to specify if you're curious about, just wanna watch or you're one yourself. Some might not join because they don't feel "In" this group, others just join to just look after "Murrsuiter" but don't own themself one

**Comment by howlrapp** [comment]
Closing this ticket since there is no plan to maintain this application much further.

Thanks for your suggestion and have a great day!
