### ISSUE TITLE
Howlr app is unusable on Oneplus Nord N10

### ISSUE THREAD

**Issue by mortonfox** [howlrapp/howlr-app#9]
The Oneplus Nord N10 5G phone has a screen that is long but narrower than most phones with 6" screens. The Howlr app seems to be making an incorrect assumption about the screen size or screen aspect ratio, so a lot of the content ends up being off-screen. This effect is worst on the Likes, Groups, and Chats screens.

The app does not allow screenshots so I can't post one to this issue. If you have any questions on what is broken, ask me in this issue.

**Comment by QuinnLion** [comment]
This seems to occur on any device with a cutout or punch hole. It does not happen on my legacy devices with or without long screens.

A workaround at the moment is using the app in landscape mode.   

The device is Motorola G7 (xt1962-1) and Nord N10 (billie8t)

Devices this does not occur on are my LG V521 and Nexbit Robin (ether)

**Comment by Dax911** [comment]
> This seems to occur on any device with a cutout or punch hole. It does not happen on my legacy devices with or without long screens.
> 
> 
> 
> A workaround at the moment is using the app in landscape mode.   
> 
> 
> 
> The device is Motorola G7 (xt1962-1) and Nord N10 (billie8t)
> 
> 
> 
> Devices this does not occur on are my LG V521 and Nexbit Robin (ether)

More than likely this is due to a formatting error with the styles. An updated npm module may need to be used.

**Comment by howlrapp** [comment]
It may be due to https://github.com/facebook/react-native/issues/23693 or https://github.com/facebook/react-native/issues/27231, we are currently looking into the various workarounds. Thanks for reporting this issue!

**Comment by howlrapp** [comment]
I couldn't find any issue with the latest version and using different kind of notch and cutout in the emulator, maybe it was fixed recently in some way or another. Please reopen if you're still experiencing this issue.

**Comment by mortonfox** [comment]
I updated the app to version 25.0.0, dated July 19 2021 on the Play Store, but I still see this issue on a Nord N10. Was there another update after that?

**Comment by mortonfox** [comment]
I'm guessing this was the relevant commit to fix the issue:
https://github.com/howlrapp/howlr-app/commit/a9d853c8947624d4862d31bc438e4889d7b79fe9

And the change was made after the July 19 update. I'll wait for it to show up on Play Store.

**Comment by howlrapp** [comment]
Hello again @mortonfox! If you're still experimenting this issue can you take a screenshot and post it here? (We had to remove the code that prevented screenshots from being taken for our latest build to work correctly). 

Thank you!

**Comment by QuinnLion** [comment]
Here ya go.
![Screenshot_20210726-055802_Howlr](https://user-images.githubusercontent.com/7369081/126992724-1da1353e-dbf7-4c85-bf37-012ba434ecdc.png)

**Comment by howlrapp** [comment]
Awesome thank you! I'll get back to you as soon as I can.

**Comment by howlrapp** [comment]
Alright, can you reload the app 2 or 3 times to make sure you loaded the last javascript payload (most upgrades are just javascript updates and don't need a full upgrade from the Play Store), and let me know if it works better?

I think Expo mistakenly assumed that your device was a tablet.

**Comment by QuinnLion** [comment]
Reloaded a few times, even wiped cache, it looked like it was gonna load a new payload, but then just went to the list. No change

**Comment by howlrapp** [comment]
Alright I made another change, it should be deployed now. Can you reload the app a few times once again? Thank you!

**Comment by mortonfox** [comment]
![2021-07-26 11 24 31](https://user-images.githubusercontent.com/495892/127015505-4ee4384a-779b-47e6-815d-a7a67432e2bb.jpg)

After clearing the cache and restarting the app, it finally doesn't look like the screen is cut off at the sides. Thanks.

**Comment by howlrapp** [comment]
Awesome, thank you all for your help!

**Comment by mortonfox** [comment]
![IMAGE 2021-07-26 17:23:48](https://user-images.githubusercontent.com/495892/127061274-780807b6-880d-4684-a75d-7dbce92cd7fd.jpg)

Popups under Settings are still too wide for the screen. This is Settings/Notifications, for example.

**Comment by howlrapp** [comment]
Hello @mortonfox! I added another fix, can you reload the app twice to see if the issue persists? Thank you!

**Comment by mortonfox** [comment]
The popups under settings look good now. Thank you.
